name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Run python python-flake8 checks
      uses: julianwachholz/flake8-action@v2.0.2
    - name: Run python black code formatter
      uses: DataDog/action-py-black-formatter@v2
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Check the code coverage
      uses: AndreMiras/coveralls-python-action@v20201129

        
  
